/**
 * Continuity Manager Service
 * 
 * Manages persistent "memory banks" for each minion, enabling cross-channel
 * context retention. When a minion is about to respond in a channel, this
 * service checks if the minion has participated in OTHER channels since the
 * last interaction in the current channel, and if so, generates and merges
 * memory summaries into the minion's persistent memory bank.
 * 
 * The compiled memory context is then injected into the minion's prompts,
 * giving them awareness of what happened in other conversations.
 */

import { MinionConfig, ChatMessageData, Channel, MessageSender } from '../types';
import { LITELLM_API_KEY, LITELLM_BASE_URL } from '../constants';

// ═══════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Memory summary for a single channel, as generated by the Continuity Manager LLM
 */
export interface ChannelMemorySummary {
  channelName: string;
  channelParticipants: string[];
  channelSummary: string;
  noteworthyContext: string[];
  shortTermMemory: string[];
  longTermMemory: string[];
  relationshipDynamics: string;
  additionalNotes?: string;
  // Metadata
  lastMessageTimestamp: number;
  messageCount: number;
}

/**
 * An entry in the memory bank's rolling channel history
 */
interface ChannelMemoryEntry {
  channelId: string;
  channelName: string;
  participants: string[];
  lastProcessedTimestamp: number;
  summary: string;
  keyTakeaways: string[];
  relationshipDynamics: string;
  additionalNotes?: string;
}

/**
 * Commander-specific context that persists across all channels
 */
interface CommanderProfile {
  knownPreferences: string[];
  currentProjects: string[];
  interactionStyle: string;
  recentMoods: string[];
}

/**
 * The persistent memory bank for a single minion
 */
export interface MinionMemoryBank {
  minionId: string;
  minionName: string;
  lastUpdated: number;
  
  // Rolling window of channel memories (max 5, FIFO)
  channelMemories: ChannelMemoryEntry[];
  
  // Persistent commander context (accumulated across all interactions)
  commanderProfile: CommanderProfile;
  
  // Long-term notes that persist indefinitely
  longTermNotes: string[];
  
  // The pre-compiled context string for injection into prompts
  compiledContext: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// CONSTANTS
// ═══════════════════════════════════════════════════════════════════════════

const MAX_CHANNEL_MEMORIES = 5;
const STORAGE_KEY = 'gemini_legion_memory_banks_v1';
const CONTINUITY_MODEL = "gemini-flash-lite-latest";
const CONTINUITY_TEMPERATURE = 0.3;

// ═══════════════════════════════════════════════════════════════════════════
// PROMPT TEMPLATE
// ═══════════════════════════════════════════════════════════════════════════

const CONTINUITY_MANAGER_PROMPT = (minionName: string) => `
You are the Continuity Manager, a meta-layer AI designed to act as a pseudo-memory system for an AI agent named "${minionName}".

**You do NOT directly participate in conversations; you observe and synthesize.**

Your task is to analyze the provided conversation log and generate a structured memory summary that can be carried over to future conversations. Imagine that "${minionName}" is about to start a NEW conversation with no prior context. What information would help them maintain continuity?

## OUTPUT FORMAT
You MUST respond with a valid JSON object in exactly this format:

{
  "channelSummary": "1-3 sentences describing the overall conversation",
  "noteworthyContext": ["array", "of", "unique", "or", "useful", "things", "to", "remember"],
  "shortTermMemory": ["immediate", "relevant", "details", "from", "recent", "messages"],
  "longTermMemory": ["persistent", "facts", "that", "should", "always", "be", "remembered"],
  "relationshipDynamics": "Notable relationship dynamics between ${minionName} and other participants",
  "additionalNotes": "Optional notes that don't fit elsewhere but are important to retain",
  "commanderInsights": {
    "preferences": ["any", "newly", "learned", "preferences"],
    "projects": ["any", "mentioned", "projects"],
    "interactionStyle": "any observations about how the Commander likes to interact"
  }
}

**IMPORTANT GUIDELINES:**
1. Focus on information that would be useful in a NEW conversation, not just a recap
2. Keep the summary concise but informative
3. Prioritize actionable context over verbose descriptions
4. Note any unfinished tasks, pending questions, or open threads
5. Capture the emotional/relational tone, not just facts
6. LLMs tend to use injected context in forced/awkward ways. Be clear that this info is BACKGROUND KNOWLEDGE, not a script to follow

Analyze the following conversation:
`;

// ═══════════════════════════════════════════════════════════════════════════
// SERVICE IMPLEMENTATION
// ═══════════════════════════════════════════════════════════════════════════

class ContinuityManagerService {
  private memoryBanks: Map<string, MinionMemoryBank> = new Map();
  private isInitialized = false;

  // ─────────────────────────────────────────────────────────────────────────
  // INITIALIZATION & PERSISTENCE
  // ─────────────────────────────────────────────────────────────────────────

  async init(): Promise<void> {
    if (this.isInitialized) return;
    
    try {
      const stored = await this.loadFromStorage();
      for (const [id, bank] of Object.entries(stored)) {
        this.memoryBanks.set(id, bank);
      }
      this.isInitialized = true;
      console.log(`[ContinuityManager] Initialized with ${this.memoryBanks.size} memory banks`);
    } catch (error) {
      console.error('[ContinuityManager] Failed to initialize:', error);
      this.isInitialized = true; // Continue anyway with empty state
    }
  }

  private async loadFromStorage(): Promise<Record<string, MinionMemoryBank>> {
    const value = await window.electronAPI.invoke('store:get', STORAGE_KEY, {});
    return value as Record<string, MinionMemoryBank>;
  }

  private async saveToStorage(): Promise<void> {
    const data: Record<string, MinionMemoryBank> = {};
    for (const [id, bank] of this.memoryBanks) {
      data[id] = bank;
    }
    await window.electronAPI.invoke('store:set', STORAGE_KEY, data);
  }

  // ─────────────────────────────────────────────────────────────────────────
  // MEMORY BANK MANAGEMENT
  // ─────────────────────────────────────────────────────────────────────────

  private getOrCreateBank(minionId: string, minionName: string): MinionMemoryBank {
    let bank = this.memoryBanks.get(minionId);
    if (!bank) {
      bank = {
        minionId,
        minionName,
        lastUpdated: Date.now(),
        channelMemories: [],
        commanderProfile: {
          knownPreferences: [],
          currentProjects: [],
          interactionStyle: '',
          recentMoods: [],
        },
        longTermNotes: [],
        compiledContext: '',
      };
      this.memoryBanks.set(minionId, bank);
    }
    return bank;
  }

  /**
   * Get the compiled memory context for a minion (for prompt injection)
   */
  getCompiledContextForMinion(minionId: string): string {
    const bank = this.memoryBanks.get(minionId);
    return bank?.compiledContext || '';
  }

  // ─────────────────────────────────────────────────────────────────────────
  // STALE CHANNEL DETECTION
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Find channels where the minion has participated since the last message
   * in the target channel
   */
  private findStaleChannels(
    minion: MinionConfig,
    targetChannelId: string,
    targetLastMsgTime: number,
    allChannels: Channel[],
    allMessages: Record<string, ChatMessageData[]>
  ): Channel[] {
    return allChannels.filter(channel => {
      // Skip the target channel itself
      if (channel.id === targetChannelId) return false;
      
      // Skip channels the minion isn't a member of
      if (!channel.members.includes(minion.name)) return false;
      
      const msgs = allMessages[channel.id] || [];
      if (msgs.length === 0) return false;
      
      // Check if there are messages AFTER our target channel's last message
      const hasNewerMessages = msgs.some(m => m.timestamp > targetLastMsgTime);
      if (!hasNewerMessages) return false;
      
      // Check if the minion actually PARTICIPATED (sent messages) after that time
      const minionParticipated = msgs.some(
        m => m.timestamp > targetLastMsgTime && 
             m.senderName === minion.name && 
             m.senderType === MessageSender.AI
      );
      
      return minionParticipated;
    });
  }

  private getLastMessageTime(
    channelId: string, 
    allMessages: Record<string, ChatMessageData[]>
  ): number {
    const msgs = allMessages[channelId] || [];
    if (msgs.length === 0) return 0;
    return msgs[msgs.length - 1].timestamp;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // MEMORY GENERATION & MERGING
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Format conversation messages for the Continuity Manager LLM
   */
  private formatMessagesForContinuity(
    messages: ChatMessageData[],
    channel: Channel
  ): string {
    const lines = [
      `Channel: ${channel.name}`,
      `Type: ${channel.type}`,
      `Participants: ${channel.members.join(', ')}`,
      `Message Count: ${messages.length}`,
      '',
      '--- CONVERSATION LOG ---',
      ''
    ];

    // Include all messages (the continuity model has high context window)
    for (const msg of messages) {
      const timestamp = new Date(msg.timestamp).toLocaleString();
      let prefix = `[${msg.senderName}]`;
      
      if (msg.senderType === MessageSender.User) {
        prefix = `[COMMANDER ${msg.senderName}]`;
      } else if (msg.senderType === MessageSender.AI) {
        prefix = `[MINION ${msg.senderName}]`;
      } else if (msg.senderType === MessageSender.System) {
        prefix = `[SYSTEM]`;
      } else if (msg.senderType === MessageSender.Tool) {
        prefix = `[TOOL for ${msg.senderName}]`;
      }

      lines.push(`${timestamp} ${prefix}: ${msg.content}`);
    }

    return lines.join('\n');
  }

  /**
   * Call the Continuity Manager LLM to generate a memory summary
   */
  private async generateChannelMemory(
    minion: MinionConfig,
    channel: Channel,
    messages: ChatMessageData[]
  ): Promise<ChannelMemorySummary | null> {
    const prompt = CONTINUITY_MANAGER_PROMPT(minion.name);
    const conversationLog = this.formatMessagesForContinuity(messages, channel);
    const fullPrompt = prompt + '\n\n' + conversationLog;

    try {
      const response = await fetch(`${LITELLM_BASE_URL}/chat/completions`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${LITELLM_API_KEY}`,
        },
        body: JSON.stringify({
          model: CONTINUITY_MODEL,
          messages: [{ role: 'user', content: fullPrompt }],
          temperature: CONTINUITY_TEMPERATURE,
          response_format: { type: 'json_object' },
        }),
      });

      if (!response.ok) {
        const error = await response.text();
        console.error('[ContinuityManager] LLM call failed:', error);
        return null;
      }

      const data = await response.json();
      const content = data.choices?.[0]?.message?.content;
      
      if (!content) {
        console.error('[ContinuityManager] Empty response from LLM');
        return null;
      }

      const parsed = JSON.parse(content);
      
      return {
        channelName: channel.name,
        channelParticipants: channel.members,
        channelSummary: parsed.channelSummary || '',
        noteworthyContext: parsed.noteworthyContext || [],
        shortTermMemory: parsed.shortTermMemory || [],
        longTermMemory: parsed.longTermMemory || [],
        relationshipDynamics: parsed.relationshipDynamics || '',
        additionalNotes: parsed.additionalNotes || '',
        lastMessageTimestamp: messages.length > 0 ? messages[messages.length - 1].timestamp : Date.now(),
        messageCount: messages.length,
      };
    } catch (error) {
      console.error('[ContinuityManager] Error generating memory:', error);
      return null;
    }
  }

  /**
   * Merge a new channel memory into the minion's memory bank
   * Uses FIFO for the rolling channel window (max 5)
   */
  private mergeChannelMemoryIntoBank(
    bank: MinionMemoryBank,
    channelId: string,
    summary: ChannelMemorySummary
  ): void {
    // Check if we already have a memory for this channel
    const existingIndex = bank.channelMemories.findIndex(m => m.channelId === channelId);
    
    const newEntry: ChannelMemoryEntry = {
      channelId,
      channelName: summary.channelName,
      participants: summary.channelParticipants,
      lastProcessedTimestamp: summary.lastMessageTimestamp,
      summary: summary.channelSummary,
      keyTakeaways: [...summary.noteworthyContext, ...summary.shortTermMemory].slice(0, 5),
      relationshipDynamics: summary.relationshipDynamics,
      additionalNotes: summary.additionalNotes,
    };

    if (existingIndex !== -1) {
      // Update existing entry
      bank.channelMemories[existingIndex] = newEntry;
    } else {
      // Add new entry
      bank.channelMemories.push(newEntry);
      
      // Enforce FIFO: remove oldest if we exceed max
      if (bank.channelMemories.length > MAX_CHANNEL_MEMORIES) {
        // Sort by timestamp, remove the oldest
        bank.channelMemories.sort((a, b) => a.lastProcessedTimestamp - b.lastProcessedTimestamp);
        bank.channelMemories.shift(); // Remove oldest
      }
    }

    // Merge long-term memory (dedupe, limit to 10)
    const allLongTerm = [...bank.longTermNotes, ...summary.longTermMemory];
    const uniqueLongTerm = [...new Set(allLongTerm)];
    bank.longTermNotes = uniqueLongTerm.slice(-10);

    // Sort channel memories by recency for display
    bank.channelMemories.sort((a, b) => b.lastProcessedTimestamp - a.lastProcessedTimestamp);

    // Recompile the context
    bank.compiledContext = this.compileContextFromBank(bank);
    bank.lastUpdated = Date.now();
  }

  /**
   * Compile the memory bank into a text context for prompt injection
   */
  private compileContextFromBank(bank: MinionMemoryBank): string {
    if (bank.channelMemories.length === 0 && bank.longTermNotes.length === 0) {
      return '';
    }

    let ctx = `
<MEMORY_CONTEXT>
## Cross-Conversation Memory

**NOTE:** This is your accumulated memory from other conversations. Use it naturally to inform your responses, but don't explicitly reference it unless truly relevant. This is background knowledge, not a script.

`;

    // Add commander profile if we have meaningful data
    const cp = bank.commanderProfile;
    if (cp.interactionStyle || cp.knownPreferences.length > 0 || cp.currentProjects.length > 0) {
      ctx += `### About Commander Steven\n`;
      if (cp.interactionStyle) {
        ctx += `- Interaction Style: ${cp.interactionStyle}\n`;
      }
      if (cp.knownPreferences.length > 0) {
        ctx += `- Known Preferences: ${cp.knownPreferences.join(', ')}\n`;
      }
      if (cp.currentProjects.length > 0) {
        ctx += `- Current Projects: ${cp.currentProjects.join(', ')}\n`;
      }
      ctx += '\n';
    }

    // Add channel memories (already sorted by recency)
    if (bank.channelMemories.length > 0) {
      ctx += `### Recent Conversations Elsewhere\n`;
      
      for (const mem of bank.channelMemories) {
        ctx += `\n**${mem.channelName}** (${mem.participants.filter(p => p !== bank.minionName).join(', ')}):\n`;
        ctx += `${mem.summary}\n`;
        
        if (mem.keyTakeaways.length > 0) {
          ctx += `Key points: ${mem.keyTakeaways.slice(0, 3).join('; ')}\n`;
        }
        
        if (mem.relationshipDynamics) {
          ctx += `Dynamics: ${mem.relationshipDynamics}\n`;
        }
      }
      ctx += '\n';
    }

    // Add long-term notes if any
    if (bank.longTermNotes.length > 0) {
      ctx += `### Long-Term Notes\n`;
      ctx += bank.longTermNotes.slice(-5).map(n => `- ${n}`).join('\n');
      ctx += '\n';
    }

    ctx += `</MEMORY_CONTEXT>`;
    
    return ctx;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // MAIN ENTRY POINT
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Main entry point: Prepare minions for a channel by updating their memory banks
   * with any stale channel context. This should be called BEFORE processing a message.
   * 
   * @returns true if any memory updates were made
   */
  async prepareMinionsForChannel(
    targetChannelId: string,
    minionsInChannel: MinionConfig[],
    allChannels: Channel[],
    allMessages: Record<string, ChatMessageData[]>
  ): Promise<boolean> {
    if (!this.isInitialized) {
      await this.init();
    }

    const targetChannelLastMsgTime = this.getLastMessageTime(targetChannelId, allMessages);
    let anyUpdates = false;

    for (const minion of minionsInChannel) {
      const staleChannels = this.findStaleChannels(
        minion,
        targetChannelId,
        targetChannelLastMsgTime,
        allChannels,
        allMessages
      );

      if (staleChannels.length > 0) {
        console.log(`[ContinuityManager] ${minion.name} has ${staleChannels.length} stale channel(s) to process`);

        for (const channel of staleChannels) {
          const messages = allMessages[channel.id] || [];
          
          // Only process if there are messages
          if (messages.length === 0) continue;

          console.log(`[ContinuityManager] Processing ${channel.name} for ${minion.name}...`);
          
          const summary = await this.generateChannelMemory(minion, channel, messages);
          
          if (summary) {
            const bank = this.getOrCreateBank(minion.id, minion.name);
            this.mergeChannelMemoryIntoBank(bank, channel.id, summary);
            anyUpdates = true;
            
            console.log(`[ContinuityManager] Updated ${minion.name}'s memory with ${channel.name}`);
          }
        }
      }
    }

    // Save if any updates were made
    if (anyUpdates) {
      await this.saveToStorage();
    }

    return anyUpdates;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // DEBUG / UTILITY
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Get the raw memory bank for a minion (for debugging/UI)
   */
  getMemoryBank(minionId: string): MinionMemoryBank | undefined {
    return this.memoryBanks.get(minionId);
  }

  /**
   * Clear all memory banks (for debugging)
   */
  async clearAllMemories(): Promise<void> {
    this.memoryBanks.clear();
    await this.saveToStorage();
    console.log('[ContinuityManager] All memory banks cleared');
  }

  /**
   * Clear memory for a specific minion
   */
  async clearMinionMemory(minionId: string): Promise<void> {
    this.memoryBanks.delete(minionId);
    await this.saveToStorage();
    console.log(`[ContinuityManager] Memory bank cleared for minion ${minionId}`);
  }
}

// Export singleton instance
export const continuityManagerService = new ContinuityManagerService();
